controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    vaccum_base_controller:
      type: diff_drive_controller/DiffDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

      

vaccum_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.178
    wheels_per_side: 2
    wheel_radius: 0.022

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: true
    linear.x.max_velocity: 0.675
    linear.x.min_velocity: -0.675
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: true
    angular.z.max_velocity: 1
    angular.z.min_velocity: -1
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration:s -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
    use_stamped_vel: false

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController

    joints:
      - left_arm_joint
      - left_middle_arm_to_base_joint
      - right_arm_joint
      - right_middle_arm_to_base_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.02
      left_arm_joint:
        trajectory: 0.5
        goal: 0.1
      left_middle_arm_to_base_joint:
        trajectory: 0.5
        goal: 0.1
      right_arm_joint:
        trajectory: 0.5
        goal: 0.1
      right_middle_arm_to_base_joint:
        trajectory: 0.5
        goal: 0.1

